//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildIndia.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class NasscomEntities : DbContext
    {
        public NasscomEntities()
            : base("name=NasscomEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Compactor> Compactor { get; set; }
        public DbSet<Complains> Complains { get; set; }
        public DbSet<DeploymentSheet> DeploymentSheet { get; set; }
        public DbSet<Location> Location { get; set; }
        public DbSet<Route> Route { get; set; }
        public DbSet<Staff> Staff { get; set; }
        public DbSet<StaffType> StaffType { get; set; }
        public DbSet<Vehicle> Vehicle { get; set; }
    
        public virtual ObjectResult<usp_FetchDeploymentSheetByDate_Result> usp_FetchDeploymentSheetByDate(Nullable<System.DateTime> deploymentDate)
        {
            var deploymentDateParameter = deploymentDate.HasValue ?
                new ObjectParameter("DeploymentDate", deploymentDate) :
                new ObjectParameter("DeploymentDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_FetchDeploymentSheetByDate_Result>("usp_FetchDeploymentSheetByDate", deploymentDateParameter);
        }
    
        public virtual ObjectResult<usp_FetchStaffByRouteNo_Result> usp_FetchStaffByRouteNo(string routeNo, Nullable<int> staffType)
        {
            var routeNoParameter = routeNo != null ?
                new ObjectParameter("RouteNo", routeNo) :
                new ObjectParameter("RouteNo", typeof(string));
    
            var staffTypeParameter = staffType.HasValue ?
                new ObjectParameter("StaffType", staffType) :
                new ObjectParameter("StaffType", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_FetchStaffByRouteNo_Result>("usp_FetchStaffByRouteNo", routeNoParameter, staffTypeParameter);
        }
    }
}
